### ISSUE TITLE
数据库初始化

### ISSUE THREAD

**Issue by wby1999** [HillZhang1999/leiketang#2]
您好，这个项目是不是缺少数据库初始化的文件？

**Comment by HillZhang1999** [comment]
是的，可以自行使用sqlite3初始化相应的数据库，或者使用redis等更适合本项目的数据库。

**Comment by wby1999** [comment]
是这样，我看其他代码里涉及到Lives，Users这些表，想问一下这些表定义什么样的，分别有哪些属性。可以qq上交流一下吗？我的qq是1678359700

**Comment by HillZhang1999** [comment]
可以参考项目源代码。见附件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HillZhang1999/leiketang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月27日(星期天) 凌晨1:02
收件人:&nbsp;"HillZhang1999/leiketang"<leiketang@noreply.github.com&gt;;
抄送:&nbsp;"此心安处是吾乡"<471791641@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [HillZhang1999/leiketang] 数据库初始化 (#2)





 
是这样，我看其他代码里涉及到Lives，Users这些表，想问一下这些表定义什么样的，分别有哪些属性。可以qq上交流一下吗？我的qq是1678359700
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Live_Client.rar (64.68M, 2021年01月26日 01:08 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=746637631b1897c8299e297f1e30501c550203545d0106011d50015a5d1d560a035e1a5b5e53501e00570f575c520752545f5605383f627f5910523c7b5c0b565e1219115942620e&code=0f7c80b3

**Comment by wby1999** [comment]
收到，谢谢
